# Generated by Django 4.0.4 on 2022-05-01 02:35

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enc_char', encrypted_fields.fields.EncryptedCharField(blank=True, default='test', max_length=10)),
            ],
        ),
    ]
